Repository UnirCs/DWFS-PER11090-2425, pull requests merged in 2024-11, with the labels that each got.

#3 Esto es una prueba
  Tema_1/Juan_Sebastian_Tellez_Montes/CV/index.html
  Tema_1/Juan_Sebastian_Tellez_Montes/CV/styles.css
  Tema_1/Juan_Sebastian_Tellez_Montes/CV/tellez.jpg
  Tema_1/Juan_Sebastian_Tellez_Montes/Cinema/index.html
  Tema_1/Juan_Sebastian_Tellez_Montes/Cinema/style.css
Labels: EJERCICIO INCOMPLETO

#29 Tarea1, Ejercicio 1 y2
  Tema_1/Nixon_Mauricio_Ramon_Gomez/CV/Foto.jpg
  Tema_1/Nixon_Mauricio_Ramon_Gomez/CV/index.html
  Tema_1/Nixon_Mauricio_Ramon_Gomez/CV/styles.css
  Tema_1/Nixon_Mauricio_Ramon_Gomez/Cinema/index.html
  Tema_1/Nixon_Mauricio_Ramon_Gomez/Cinema/styles.css
Labels: SE NECESITAN CAMBIOS

#32 Esto es una prueba
  Tema_1/Jhon_Edisson_Salguero_Pinzon/CV/favicon.ico
  Tema_1/Jhon_Edisson_Salguero_Pinzon/CV/foto.jpg
  Tema_1/Jhon_Edisson_Salguero_Pinzon/CV/index.html
  Tema_1/Jhon_Edisson_Salguero_Pinzon/CV/styles.css
  Tema_1/Jhon_Edisson_Salguero_Pinzon/Cinema/index.html
  Tema_1/Jhon_Edisson_Salguero_Pinzon/Cinema/styles.css
Labels: EJERCICIO INCOMPLETO

#59 ejercicios 1 y 2
  Tema_1/Jose_Maria_Blasco_Roman/CV/index.html
  Tema_1/Jose_Maria_Blasco_Roman/CV/mini.jpg
  Tema_1/Jose_Maria_Blasco_Roman/CV/styles.css
  Tema_1/Jose_Maria_Blasco_Roman/Cine/index.html
  Tema_1/Jose_Maria_Blasco_Roman/Cine/returnoftheking.webp
  Tema_1/Jose_Maria_Blasco_Roman/Cine/styles.css
Labels: SE NECESITAN CAMBIOS

#44 Actividad 1 y 2
  Tema_1/Andres_Felipe_Toro_Nuñez/CV/Andres_Toro.jpg
  Tema_1/Andres_Felipe_Toro_Nuñez/CV/index.html
  Tema_1/Andres_Felipe_Toro_Nuñez/CV/styles.css
  Tema_1/Andres_Felipe_Toro_Nuñez/Cinema/index.html
  Tema_1/Andres_Felipe_Toro_Nuñez/Cinema/styles.css
Labels: SE NECESITAN CAMBIOS

#55 Tema 1: ejercicios cv y cinema
  Tema_1/Cesar_Ramirez_Vega/cinema/index.html
  Tema_1/Cesar_Ramirez_Vega/cinema/styles.css
  Tema_1/Cesar_Ramirez_Vega/cv/cv-image.png
  Tema_1/Cesar_Ramirez_Vega/cv/index.html
  Tema_1/Cesar_Ramirez_Vega/cv/styles.css
Labels: SE NECESITAN CAMBIOS

#50 No puedo hacer pull request
  Tema_1/Raúl_Antonio_Castro_Cepulo/Ejercicio 1/fotoRcc.png
  Tema_1/Raúl_Antonio_Castro_Cepulo/Ejercicio 1/index.html
  Tema_1/Raúl_Antonio_Castro_Cepulo/Ejercicio 1/styles.css
  Tema_1/Raúl_Antonio_Castro_Cepulo/Ejercicio 2/index.html
  Tema_1/Raúl_Antonio_Castro_Cepulo/Ejercicio 2/styles.css
  Tema_1/Raúl_Antonio_Castro_Cepulo/Ejercicio 2/unirCinemaRCC.png
Labels: SE NECESITAN CAMBIOS

#64 PR: se suben actividades tema_2
  Tema_2/Fanor_Hernan_Quintero_Atara/cinema/cinema.js
  Tema_2/Fanor_Hernan_Quintero_Atara/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#80 Ejercicios Tema 2
  Tema_2/Jon_Lopez_Carrillo/Ejercicio1/actividad.js
  Tema_2/Jon_Lopez_Carrillo/Ejercicio2/cinema.js
Labels: SE NECESITAN CAMBIOS

#73 Tarea tema 1
  Tema_1/JONATHAN_ANDRES_QUISHPE_CATAGÑA/CINEMA/index.html
  Tema_1/JONATHAN_ANDRES_QUISHPE_CATAGÑA/CINEMA/style.css
  Tema_1/JONATHAN_ANDRES_QUISHPE_CATAGÑA/CV/index.html
  Tema_1/JONATHAN_ANDRES_QUISHPE_CATAGÑA/CV/style.css
  Tema_2/JONATHAN_ANDRES_QUISHPE_CATAGÑA/Cinema/cinema.js
  Tema_2/JONATHAN_ANDRES_QUISHPE_CATAGÑA/Filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#89 Ejercicios de Tema 2
  Tema_2/Mario_Alberto_Ibarra_Martinez/Cinema/seatingSuggestion.js
  Tema_2/Mario_Alberto_Ibarra_Martinez/Filters/actividad.js
Labels: SE NECESITAN CAMBIOS

#95 Ejercicios Tema 2
  Tema_2/David_Alfredo_Davila_Garzon/Cinema/cinema.js
  Tema_2/David_Alfredo_Davila_Garzon/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#106 José Luis Yépez García - Ejercicios Tema 2: Cinema, Filtros
  Tema_2/Jose_Luis_Yepez_Garcia/Cinema/butacas.js
  Tema_2/Jose_Luis_Yepez_Garcia/Filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#109 Unir Tema2 Jhon Roberth Fernandez
  Tema_2/Jhon_Roberth_Fernandez_Ortiz/cinema/cinema.js
  Tema_2/Jhon_Roberth_Fernandez_Ortiz/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#123 Entrega ejercicios tema 2 - Melvy Martinez
  Tema_2/Melvy_Martinez/cinema/cinema.js
  Tema_2/Melvy_Martinez/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#126 Ejercicios Tema 2 filtros y cinema - Cristian Alejandro Castillo Salguero
  Tema_2/Cristian_Alejandro_Castillo_Salguero/cinema/cinema.js
  Tema_2/Cristian_Alejandro_Castillo_Salguero/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#99 Tarea 2
  Tema_2/Ricardo_David_Falcon_Falcon/cinema/cinema.js
  Tema_2/Ricardo_David_Falcon_Falcon/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#138 Ejercicios filtro y cinemajs. Luis Oslé García
  Tema_2/Luis_Osle_Garcia/cinema/cinema.js
  Tema_2/Luis_Osle_Garcia/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#130 Actividad de la Introducción a JavaScript
  Tema_2/Tatiana_Paola_Zambrano_Vasquez/cinema/cinema.js
  Tema_2/Tatiana_Paola_Zambrano_Vasquez/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#135 Entrega Tema 1 y Tema 2 Jaime Granel Tejedor
  Tema_1/Jaime_Granel_Tejedor/CV/cvjg.png
  Tema_1/Jaime_Granel_Tejedor/CV/index.html
  Tema_1/Jaime_Granel_Tejedor/CV/styles.css
  Tema_1/Jaime_Granel_Tejedor/Cinema/index.html
  Tema_1/Jaime_Granel_Tejedor/Cinema/styles.css
  Tema_2/Jaime_Granel_Tejedor/Cinema/Cinema.js
  Tema_2/Jaime_Granel_Tejedor/Filtro/actividad.js
Labels: SE NECESITAN CAMBIOS

#76 Ejercicios 1 y 2 del tema 1
  Tema_1/German_Camara_Jimenez/Ejercicio_1/foto2.PNG
  Tema_1/German_Camara_Jimenez/Ejercicio_1/index.html
  Tema_1/German_Camara_Jimenez/Ejercicio_1/styles.css
  Tema_1/German_Camara_Jimenez/Ejercicio_2/index.html
  Tema_1/German_Camara_Jimenez/Ejercicio_2/style.css
  Tema_2/German_Camara_Jimenez/Cine/cine.js
  Tema_2/German_Camara_Jimenez/Filtros/actividad.js
Labels: PR INCORRECTA

#158 Ejercicios numero 1 y 2 - Tema 2
  Tema_2/Miguel_Angel_Hernandez_Munoz/Cinema/cinema.js
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/ImageHandler.js
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/actividad.js
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/input/cat.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/input/dog.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/input/tucan.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/ejemplo.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/merged.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/tucan_black_and_white.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/tucan_blue.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/tucan_dimed.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/tucan_green.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/tucan_grey.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/tucan_inverse.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/tucan_red.jpg
  Tema_2/Miguel_Angel_Hernandez_Munoz/Filtros/output/tucan_scale_down.jpg
Labels: SE NECESITAN CAMBIOS

#102 Entrega Ejercicio 2
  Tema_1/David_Gilarranz_Ortega/Ejercicio_2/index.html
  Tema_1/David_Gilarranz_Ortega/Ejercicio_2/styles.css
  Tema_3/David_Gilarranz_Ortega/Promesas/index.html
  Tema_3/David_Gilarranz_Ortega/Promesas/styles.css
Labels: PR INCORRECTA

#156 Add files via upload
  Tema_2/Unai_Flores_Nieto/CineUNIR/cine2.js
  Tema_2/Unai_Flores_Nieto/Filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#108 Envio solución ejercicio Cinema y Filtros-Tema2
  Tema_2/Jhon_Edisson_Salguero_Pinzon/Cinema/cinema.js
  Tema_2/Jhon_Edisson_Salguero_Pinzon/Filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#152 Ejercicios completos tema 2
  Tema_2/Angel_Xavier_Cobos_Andrango/cinema/actividad.js
Labels: SE NECESITAN CAMBIOS

#180 Corrección Tema 1
  Tema_1/Yusly_Yulipsa_Arboleda_Palacios/CV/Yusly_foto.png
  Tema_1/Yusly_Yulipsa_Arboleda_Palacios/CV/index.html
  Tema_1/Yusly_Yulipsa_Arboleda_Palacios/CV/styles.css
  Tema_1/Yusly_Yulipsa_Arboleda_Palacios/Cinema/index.html
  Tema_1/Yusly_Yulipsa_Arboleda_Palacios/Cinema/styles.css
Labels: PR INCORRECTA

#94 Tema 2
  Tema_2/Jordan_Enrique_Espinosa_Vinueza/cinema/cinema.js
  Tema_2/Jordan_Enrique_Espinosa_Vinueza/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#167 Ejercicios Tema 3 + Corrección ejercicio tema 2
  Tema_2/Jorge_Romeral_Morales/02_Cine/script.js
  Tema_3/Jorge_Romeral_Morales/01_Chuck/index.html
  Tema_3/Jorge_Romeral_Morales/01_Chuck/script.js
  Tema_3/Jorge_Romeral_Morales/01_Chuck/styles.css
  Tema_3/Jorge_Romeral_Morales/02_Cine/index.html
  Tema_3/Jorge_Romeral_Morales/02_Cine/script.js
  Tema_3/Jorge_Romeral_Morales/02_Cine/styles.css
Labels: SE NECESITAN CAMBIOS

#190 Ejercicios Tema 2 Alejandro Quintana Escribano
  Tema_2/Alejandro_Quintana_Escribano/Cinema/cinema.js
  Tema_2/Alejandro_Quintana_Escribano/Filtros/filtros.js
Labels: SE NECESITAN CAMBIOS

#226 Ejercicios tema 2
  Tema_2/Jefferson_Rodriguez_Rodriguez/cinema/cinema.js
  Tema_2/Jefferson_Rodriguez_Rodriguez/filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#230 feat(Enrique_Teruel_Gutierrez): tema 1, tema 2, tema 3, tema 4
  Tema_1/Enrique_Teruel_Gutierrez/CV/assets/hero.jpg
  Tema_1/Enrique_Teruel_Gutierrez/CV/assets/photo.jpeg
  Tema_1/Enrique_Teruel_Gutierrez/CV/index.html
  Tema_1/Enrique_Teruel_Gutierrez/CV/styles/normalize.css
  Tema_1/Enrique_Teruel_Gutierrez/CV/styles/styles.css
  Tema_1/Enrique_Teruel_Gutierrez/Cinema/assets/screen.svg
  Tema_1/Enrique_Teruel_Gutierrez/Cinema/assets/seat.svg
  Tema_1/Enrique_Teruel_Gutierrez/Cinema/assets/selected-seat.svg
  Tema_1/Enrique_Teruel_Gutierrez/Cinema/components/seat-selector.js
  Tema_1/Enrique_Teruel_Gutierrez/Cinema/index.html
  Tema_1/Enrique_Teruel_Gutierrez/Cinema/mock.png
  Tema_1/Enrique_Teruel_Gutierrez/Cinema/styles/normalize.css
  Tema_1/Enrique_Teruel_Gutierrez/Cinema/styles/styles.css
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/assets/screen.svg
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/assets/seat.svg
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/assets/selected-seat.svg
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/components/seat-selector.js
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/index.html
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/js/reservation-system.js
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/js/seat-handler.js
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/styles/normalize.css
  Tema_2/Enrique_Teruel_Gutierrez/Cinema/styles/styles.css
  Tema_2/Enrique_Teruel_Gutierrez/filtros/actividad.js
  Tema_3/Enrique_Teruel_Gutierrez/Chuck/Readme.md
  Tema_3/Enrique_Teruel_Gutierrez/Chuck/index.html
  Tema_3/Enrique_Teruel_Gutierrez/Chuck/js/chuck-handler.js
  Tema_3/Enrique_Teruel_Gutierrez/Chuck/styles/styles.css
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/assets/screen.svg
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/assets/seat.svg
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/assets/selected-seat.svg
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/components/seat-selector.js
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/index.html
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/js/reservation-system.js
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/js/seat-handler.js
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/styles/normalize.css
  Tema_3/Enrique_Teruel_Gutierrez/Cinema/styles/styles.css
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/assets/screen.svg
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/assets/seat.svg
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/assets/selected-seat.svg
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/cinema.html
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/components/seat-selector.js
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/index.html
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/js/reservation-system.js
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/js/seat-handler.js
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/js/validations.js
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/styles/login.css
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/styles/normalize.css
  Tema_4/Enrique_Teruel_Gutierrez/Cinema/styles/styles.css
Labels: SE NECESITAN CAMBIOS

#217 Ejercicios Tema 2
  Tema_2/Nexar Cedeño Ponce/Cinema/cinema.js
  Tema_2/Nexar Cedeño Ponce/Filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#234 Tema 2. Ejercicios Filtros y Cinema
  Tema_2/JoseMaria_DeTena_Rubio/Cinema/cinema.js
  Tema_2/JoseMaria_DeTena_Rubio/Filtros/actividad.js
Labels: SE NECESITAN CAMBIOS

#238 Actividad #4
  Tema_4/Theddy_Esthyveen_Luna_Marin/Cinema/cinema.css
  Tema_4/Theddy_Esthyveen_Luna_Marin/Cinema/cinema.html
  Tema_4/Theddy_Esthyveen_Luna_Marin/Cinema/cinema.js
  Tema_4/Theddy_Esthyveen_Luna_Marin/Cinema/registro.css
  Tema_4/Theddy_Esthyveen_Luna_Marin/Cinema/registro.html
  Tema_4/Theddy_Esthyveen_Luna_Marin/Cinema/registro.js
Labels: SE NECESITAN CAMBIOS

#242 Resubida de los ejercicios del tema 2
  Tema_2/German_Camara_Jimenez/Cine/cine.js
Labels: PR INCORRECTA
