Repository UnirCs/DWFS-PER11090-2425, pull requests merged in 2025-02, with the labels that each got.

#382 Actividad 4
  Tema_4/Hector_Gonzalez_Tabares/cinema/css/styles.css
  Tema_4/Hector_Gonzalez_Tabares/cinema/css/stylesCinema.css
  Tema_4/Hector_Gonzalez_Tabares/cinema/html/cinema.html
  Tema_4/Hector_Gonzalez_Tabares/cinema/html/index.html
  Tema_4/Hector_Gonzalez_Tabares/cinema/js/cinema.js
  Tema_4/Hector_Gonzalez_Tabares/cinema/js/script.js
  Tema_6/Hector_Gonzalez_Tabares/calculadora/calculadora.md
  Tema_6/Hector_Gonzalez_Tabares/cinema/cinema.md
  Tema_6/Hector_Gonzalez_Tabares/hundelaflota/hunde_la_flota.md
  Tema_8/Hector_Gonzalez_Tabares/calculadora/.mvn/wrapper/maven-wrapper.properties
  Tema_8/Hector_Gonzalez_Tabares/calculadora/HELP.md
  Tema_8/Hector_Gonzalez_Tabares/calculadora/mvnw
  Tema_8/Hector_Gonzalez_Tabares/calculadora/mvnw.cmd
  Tema_8/Hector_Gonzalez_Tabares/calculadora/pom.xml
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/CalculadoraApplication.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/controller/CalculatorController.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/data/OperationRepository.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/dto/OperationRequestDTO.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/dto/OperationResponseDTO.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/dto/PowerRequestDTO.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/dto/RootRequestDTO.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/dto/TwoNumberRequestDTO.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/modelo/Operacion.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/service/OperacionesService.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/java/com/calculadora/service/OperacionesServiceImpl.java
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/resources/application.yml
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/main/resources/data.sql
  Tema_8/Hector_Gonzalez_Tabares/calculadora/src/test/java/com/calculadora/CalculadoraApplicationTests.java
Labels: PR INCORRECTA

#366 Tarea 6
  Tema_6/Julio_Cesar_Sarauz_Rivadeneira/calculadora/Readme.md
  Tema_6/Julio_Cesar_Sarauz_Rivadeneira/cinema/Readme.md
  Tema_6/Julio_Cesar_Sarauz_Rivadeneira/hundelaflota/Readme.md
  Tema_6/Julio_Cesar_Sarauz_Rivadeneira/hundelaflota/Untitled-1.cpp
Labels: SE NECESITAN CAMBIOS

#391 Tema 8 - Ejercicio 5
  Tema_8/Álvaro_García_Infante/GatewayACL/pom.xml
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/GatewayAndFiltersApplication.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/config/MapperConfig.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/decorator/DeleteRequestDecorator.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/decorator/GetRequestDecorator.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/decorator/PatchRequestDecorator.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/decorator/PostRequestDecorator.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/decorator/PutRequestDecorator.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/decorator/RequestDecoratorFactory.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/filter/RequestTranslationFilter.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/model/GatewayRequest.java
  Tema_8/Álvaro_García_Infante/GatewayACL/src/main/java/com/unir/gateway/utils/RequestBodyExtractor.java
Labels: EJERCICIO INCOMPLETO

#395 Subida de Tema_1 Curriculum y Cinema
  Tema_1/Fajardo_Romero_Ines_Janellys/cinema/css/style.css
  Tema_1/Fajardo_Romero_Ines_Janellys/cinema/img/cinema.webp
  Tema_1/Fajardo_Romero_Ines_Janellys/cinema/index.html
  Tema_1/Fajardo_Romero_Ines_Janellys/cv/css/style.css
  Tema_1/Fajardo_Romero_Ines_Janellys/cv/image/avatarFemenino.jfif
  Tema_1/Fajardo_Romero_Ines_Janellys/cv/index.html
Labels: SE NECESITAN CAMBIOS

#404 Actividad 8 (Calculadora + Gateway ACL)
  Tema_8/Yovani_Royero_Mena/Calculadora/pom.xml
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/CalculadoraApplication.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/domain/Numero.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/domain/Operacion.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/repository/NumeroRepository.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/repository/OperacionRepository.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/service/OperacionService.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/service/dto/MultiploDTO.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/service/dto/NumeroDTO.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/service/dto/OperacionDTO.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/service/impl/OperacionServiceImpl.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/service/utils/Constantes.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/web/rest/OperacionResource.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/web/rest/exception/NotFoundException.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/web/rest/payload/MultiploPayload.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/java/com/unir/calculadora/web/rest/payload/NumberPayload.java
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/resources/application.yml
  Tema_8/Yovani_Royero_Mena/Calculadora/src/main/resources/data.sql
  Tema_8/Yovani_Royero_Mena/Calculadora/src/test/java/com/unir/calculadora/CalculadoraApplicationTests.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/pom.xml
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/GatewayAndFiltersApplication.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/config/MapperConfig.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/decorator/DeleteRequestDecorator.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/decorator/GetRequestDecorator.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/decorator/PatchRequestDecorator.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/decorator/PostRequestDecorator.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/decorator/PutRequestDecorator.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/decorator/RequestDecoratorFactory.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/filter/RequestTranslationFilter.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/model/GatewayRequest.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/java/com/unir/gateway/utils/RequestBodyExtractor.java
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/main/resources/application.yml
  Tema_8/Yovani_Royero_Mena/GatewayACL/src/test/java/com/unir/gateway/GatewayAndFiltersApplicationTests.java
Labels: PROPUESTA DE MEJORA

#409 Tema 8. Ejercicios 1,2,3
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/.gitattributes
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/.gitignore
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/.mvn/wrapper/maven-wrapper.properties
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/Calculadora_Microservice_Collection.json
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/H2_ok.png
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/HELP.md
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/Swagger.jpg
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/SwaggerOK.png
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/mvnw
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/mvnw.cmd
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/pom.xml
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/java/blasco/calculadora/CalculadoraApplication.java
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/java/blasco/calculadora/config/SwaggerConfig.java
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/java/blasco/calculadora/controller/OperationsController.java
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/java/blasco/calculadora/controller/model/OperationDto.java
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/java/blasco/calculadora/data/OperationsRepository.java
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/java/blasco/calculadora/data/model/CalculatorOperation.java
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/java/blasco/calculadora/service/OperationsService.java
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/java/blasco/calculadora/service/OperationsServiceImpl.java
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/resources/application.yml
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/main/resources/data.sql
  Tema_8/Jose_Maria_Blasco_Roman/calculadora/src/test/java/blasco/calculadora/CalculadoraApplicationTests.java
Labels: SE NECESITAN CAMBIOS
