Repository UnirCs/DWFS-PER11090-2425, pull requests merged in 2025-01, with the labels that each got.

#337 Theme 6 API design
  Tema_6/David_Alfredo_Davila_Garzon/Calculadora/Readme.md
  Tema_6/David_Alfredo_Davila_Garzon/Cinema/Readme.md
  Tema_6/David_Alfredo_Davila_Garzon/Hunde_la_flota/Readme.md
Labels: SE NECESITAN CAMBIOS

#347 Correccion de errorres
  Tema_2/hugo_tovio_barreto/cinema.js
  Tema_2/hugo_tovio_barreto/filtros.js
  Tema_3/Readme.md
  Tema_3/hugo_tovio_barreto/chuck/index.html
  Tema_3/hugo_tovio_barreto/chuck/styles.css
  Tema_3/hugo_tovio_barreto/cinema/cinema.js
  Tema_3/hugo_tovio_barreto/cinema/index.html
  Tema_3/hugo_tovio_barreto/cinema/styles.css
  Tema_4/hugo_tovio_barreto/cinema.js
  Tema_4/hugo_tovio_barreto/index.html
  Tema_4/hugo_tovio_barreto/styles.css
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/.gitignore
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/README.md
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/package-lock.json
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/package.json
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/public/favicon.ico
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/public/index.html
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/public/logo192.png
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/public/logo512.png
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/public/manifest.json
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/public/robots.txt
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/App.css
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/App.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/App.test.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/Footer/Footer.css
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/Footer/Footer.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/Header/Header.css
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/Header/Header.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/ListaPelis/ListaPelis.css
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/ListaPelis/ListaPelis.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/Pelicula/Pelicula.css
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/Pelicula/Pelicula.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/Peliculas/Peliculas.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/index.css
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/index.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/logo.svg
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/reportWebVitals.js
  Tema_5/hugo_tovio_barreto/cineApp/cine_unir/src/setupTests.js
  Tema_5/hugo_tovio_barreto/cineApp/herokuUrl.txt
Labels: PR INCORRECTA

#348 Actividad 1 taller cv y cinema
  Tema_1/Alexandra_Bedoya_Muñoz/ArchivoPrueba.txt
  Tema_1/Alexandra_Bedoya_Muñoz/cinema/indx.html
  Tema_1/Alexandra_Bedoya_Muñoz/cinema/styles.css
  Tema_1/Alexandra_Bedoya_Muñoz/cv/index.html
  Tema_1/Alexandra_Bedoya_Muñoz/cv/styles.css
  Tema_2/Alexandra_Bedoya_Muñoz/cinema/indx.html
  Tema_2/Alexandra_Bedoya_Muñoz/cinema/script.js
  Tema_2/Alexandra_Bedoya_Muñoz/cinema/styles.css
  Tema_2/Alexandra_Bedoya_Muñoz/filtros/actividad.js
  Tema_3/Alexandra_Bedoya_Muñoz/chuck/index.html
  Tema_3/Alexandra_Bedoya_Muñoz/chuck/script.js
  Tema_3/Alexandra_Bedoya_Muñoz/chuck/styles.css
  Tema_3/Alexandra_Bedoya_Muñoz/cinema/indx.html
  Tema_3/Alexandra_Bedoya_Muñoz/cinema/script.js
  Tema_3/Alexandra_Bedoya_Muñoz/cinema/styles.css
  Tema_4/Alexandra_Bedoya_Muñoz/cinema/index.html
  Tema_4/Alexandra_Bedoya_Muñoz/cinema/indx.html
  Tema_4/Alexandra_Bedoya_Muñoz/cinema/script.js
  Tema_4/Alexandra_Bedoya_Muñoz/cinema/scriptButacas.js
  Tema_4/Alexandra_Bedoya_Muñoz/cinema/styles.css
  Tema_4/Alexandra_Bedoya_Muñoz/cinema/stylesButacas.css
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/.gitignore
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/README.md
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/package-lock.json
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/package.json
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/public/favicon.ico
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/public/index.html
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/public/logo192.png
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/public/logo512.png
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/public/manifest.json
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/public/robots.txt
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/App.css
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/App.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/App.test.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/components/Footer.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/components/Header.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/components/Movie.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/components/MovieList.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/index.css
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/index.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/logo.svg
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/movies.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/reportWebVitals.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/setupTests.js
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/styles/Footer.css
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/styles/Header.css
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/styles/Movie.css
  Tema_5/Alexandra_Bedoya_Muñoz/Cinema-main/Cinema-main/src/styles/MovieList.css
  Tema_5/Alexandra_Bedoya_Muñoz/Link Vercel.txt
Labels: SE NECESITAN CAMBIOS

#361 Ejercicios Tema 6
  Tema_6/Theddy_Esthyveen_Luna_Marin/Calculadora/Readme.md
  Tema_6/Theddy_Esthyveen_Luna_Marin/Cinema/Readme.md
  Tema_6/Theddy_Esthyveen_Luna_Marin/Hunde la Flota/Readme.md
Labels: SE NECESITAN CAMBIOS

#367 Tema 6
  Tema_6/JONATHAN_ANDRES_QUISHPE_CATAGÑA/Calculadora/Readme.md
  Tema_6/JONATHAN_ANDRES_QUISHPE_CATAGÑA/Cinema/Readme.md
  Tema_6/JONATHAN_ANDRES_QUISHPE_CATAGÑA/Hunde flota/Readme.md
Labels: SE NECESITAN CAMBIOS

#371 creación de API REST tema 6
  Tema_6/Tatiana_Paola_Zambrano_Vasquez/Calculadora/Calculadora.md
  Tema_6/Tatiana_Paola_Zambrano_Vasquez/Cinema/Cinema.md
  Tema_6/Tatiana_Paola_Zambrano_Vasquez/Hunde_la_flota/Hunde_la_flota.md
Labels: SE NECESITAN CAMBIOS

#372 Tema 6 - Fredy Geovanny Camacho León
  Tema_6/Fredy_Geovanny_Camacho_Leon/Calculadora/Calculadora.md
  Tema_6/Fredy_Geovanny_Camacho_Leon/Cinema/Cinema.md
  Tema_6/Fredy_Geovanny_Camacho_Leon/HundeLaFlota/HundeLaFlota.md
Labels: SE NECESITAN CAMBIOS

#377 Ejercicios Tema 6
  Tema_6/David_Martinez_Bahillo/Calculadora/ReadMe.md
  Tema_6/David_Martinez_Bahillo/Cinema/Readme.md
  Tema_6/David_Martinez_Bahillo/hundeFlota/Readme.md
Labels: SE NECESITAN CAMBIOS

#357 Ejercicio 6 Jose Fernado
  Tema_6/Jose_Fernando_Martinez/Calculadora/Calculadora.md
  Tema_6/Jose_Fernando_Martinez/Cinema/Cinema.md
  Tema_6/Jose_Fernando_Martinez/Juego hunde flota/Juego hunde flota.md
Labels: SE NECESITAN CAMBIOS

#380 ejercicios tema 6
  Tema_6/Jose_Maria_Blasco_Roman/calculadora/Readme.md
  Tema_6/Jose_Maria_Blasco_Roman/cine/Readme.md
  Tema_6/Jose_Maria_Blasco_Roman/hundirlaflota/Readme.md
Labels: SE NECESITAN CAMBIOS

#381 API Rest del tema 6
  Tema_6/Carlos_Andrés_Proaño_Valles/Calculadora/Readme.md
  Tema_6/Carlos_Andrés_Proaño_Valles/Cinema/Readme.md
  Tema_6/Carlos_Andrés_Proaño_Valles/Hunde la flota/Readme.md
Labels: SE NECESITAN CAMBIOS

#385 Gateway, put & delete decorators implementation
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/pom.xml
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/GatewayAndFiltersApplication.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/config/MapperConfig.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/decorator/DeleteRequestDecorator.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/decorator/GetRequestDecorator.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/decorator/PatchRequestDecorator.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/decorator/PostRequestDecorator.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/decorator/PutRequestDecorator.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/decorator/RequestDecoratorFactory.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/filter/RequestTranslationFilter.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/model/GatewayRequest.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/java/com/unir/gateway/utils/RequestBodyExtractor.java
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/main/resources/application.yml
  Tema_8/David_Alfredo_Davila_Garzon/GatewayACL/src/test/java/com/unir/gateway/GatewayAndFiltersApplicationTests.java
Labels: EJERCICIO INCOMPLETO
